-- Webhook endpoints: tenant-registered URLs that receive event-driven notifications.
--
-- Design notes:
--   - Tenant registers one or more URLs with a chosen set of event_types.
--   - Empty event_types array means "subscribe to all events".
--   - The secret is a 32-byte random hex string generated by the API, stored
--     plaintext (never returned in API responses after initial creation).
--     Tenants use it to verify HMAC-SHA256 signatures on incoming webhooks.
--   - Tier-limited: FREE=1, STARTER=2, GROWTH=5, BUSINESS=10 endpoints per tenant.
--   - Deregistration sets active=false (soft-delete) — past deliveries are preserved.

BEGIN;

CREATE TABLE webhook_endpoints (
  id           UUID         PRIMARY KEY DEFAULT uuid_generate_v7(),
  tenant_id    UUID         NOT NULL REFERENCES tenants(id),
  url          TEXT         NOT NULL,
  secret       TEXT         NOT NULL,
  event_types  TEXT[]       NOT NULL DEFAULT '{}',
  active       BOOLEAN      NOT NULL DEFAULT true,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- Fan-out lookup: find all active endpoints for a tenant that subscribe to an event type.
CREATE INDEX idx_webhook_endpoints_tenant_active ON webhook_endpoints(tenant_id)
  WHERE active = true;

COMMIT;
