const issuerModel = require('../models/issuer.model');
const tenantModel = require('../models/tenant.model');
const rideService = require('./ride.service');
const emailFactory = require('./email');
const invoiceAuthorizedTemplate = require('./email/templates/invoice-authorized');
const verifyEmailTemplate = require('./email/templates/verify-email');
const paymentProofSubmittedTemplate = require('./email/templates/payment-proof-submitted');
const config = require('../config');

// When APP_ENV is 'staging', every email carries a visible notice so a
// recipient can't mistake a test-environment message for a real one — the
// same distinction CLAUDE.md documents for SRI routing (ambiente), applied
// to outgoing email too. Injected here, once, rather than in every template,
// since it applies uniformly regardless of email type.
function stagingBannerText(language) {
  return language === 'en'
    ? 'TEST ENVIRONMENT — this message was generated by a staging system and does not reflect a real transaction.'
    : 'ENTORNO DE PRUEBAS — este mensaje fue generado por un sistema de staging y no refleja una transacción real.';
}

function applyStagingBanner({ text, html }, language = 'es') {
  if (config.appEnv !== 'staging') return { text, html };
  const banner = stagingBannerText(language);
  const bannerHtml = `<div style="background:#fff3cd;border:1px solid #ffeeba;color:#856404;padding:10px 16px;margin-bottom:16px;border-radius:4px;font-weight:bold;">${banner}</div>`;
  return {
    text: `${banner}\n\n${text}`,
    // Templates aren't consistent about wrapping in a full <html><body> — some
    // are body fragments (verify-email.js), some are full documents
    // (payment-reviewed.js). Insert right after <body> when present so the
    // banner renders inside the document; otherwise just prepend the fragment.
    html: /<body[^>]*>/i.test(html)
      ? html.replace(/<body[^>]*>/i, (match) => `${match}\n${bannerHtml}`)
      : `${bannerHtml}\n${html}`,
  };
}

/**
 * Generate and send the authorized invoice email with RIDE PDF and XML attached.
 * Returns { sent: true } on success, { sent: false, reason } if skipped.
 * Throws on provider error — callers decide how to handle.
 *
 * @param {object} document - DB row from documents table
 * @returns {Promise<{ sent: boolean, reason?: string }>}
 */
async function sendInvoiceAuthorized(document) {
  if (!document.buyer_email) {
    return { sent: false, reason: 'no_email' };
  }

  const issuer = await issuerModel.findById(document.issuer_id);
  const tenant = await tenantModel.findById(issuer.tenant_id);
  const ridePdf  = await rideService.generate(document);
  const xmlBytes = Buffer.from(document.authorization_xml, 'utf8');

  const language = tenant.preferred_language || 'es';
  const rendered = invoiceAuthorizedTemplate.render(document, issuer, language);
  const { subject } = rendered;
  const { text, html } = applyStagingBanner(rendered, language);
  const provider = emailFactory.getProvider();

  const from = `${issuer.business_name} via Comprobify <${config.email.fromDocuments}>`;

  const { messageId } = await provider.send({
    from,
    to: document.buyer_email,
    subject,
    text,
    html,
    attachments: [
      { filename: `RIDE-${document.access_key}.pdf`, data: ridePdf,  contentType: 'application/pdf' },
      { filename: `${document.access_key}.xml`,      data: xmlBytes, contentType: 'application/xml' },
    ],
  });

  return { sent: true, messageId };
}

async function sendVerificationEmail(email, token, redirectUrl = null, language = 'es') {
  const verificationUrl = redirectUrl
    ? `${redirectUrl}?token=${token}`
    : `${config.appBaseUrl}/v1/verify-email?token=${token}`;
  const rendered = verifyEmailTemplate.render(verificationUrl, config.verificationTokenTtlHours, language);
  const { subject } = rendered;
  const { text, html } = applyStagingBanner(rendered, language);
  const provider = emailFactory.getProvider();

  const { messageId } = await provider.send({
    from: `Comprobify <${config.email.from}>`,
    to: email,
    subject,
    text,
    html,
    attachments: [],
  });

  return { messageId };
}

/**
 * Notify the operator that a tenant uploaded payment proof needing review.
 * Skipped entirely (no-op) if ADMIN_NOTIFICATION_EMAIL is unset — this is an
 * operational convenience email, not something tenant-facing behavior depends on.
 *
 * @param {object} payment      - DB row from payments table
 * @param {object} subscription - DB row from subscriptions table
 * @param {object} tenant       - DB row from tenants table
 * @returns {Promise<{ sent: boolean, reason?: string }>}
 */
async function sendPaymentProofSubmitted(payment, subscription, tenant, referenceNumber) {
  if (!config.adminNotificationEmail) {
    return { sent: false, reason: 'no_admin_email' };
  }

  const rendered = paymentProofSubmittedTemplate.render(payment, subscription, tenant, referenceNumber);
  const { subject } = rendered;
  const { text, html } = applyStagingBanner(rendered, 'en');
  const provider = emailFactory.getProvider();

  await provider.send({
    from: `Comprobify <${config.email.from}>`,
    to: config.adminNotificationEmail,
    subject,
    text,
    html,
    attachments: [],
  });

  return { sent: true };
}

/**
 * Send an already-rendered notification email to a tenant (ADR-024,
 * NEXT_STEPS.md item 13 Phase C) — the generic counterpart of the 4
 * type-specific send*() functions this replaced (sendPaymentReviewed,
 * sendSubscriptionRenewalDue, sendSubscriptionExpired,
 * sendPriceChangeAnnounced). Rendering (which template, which language,
 * which values) is entirely notificationEmailTemplateService's job now —
 * this function only applies the staging banner and dispatches through the
 * provider, exactly like every other send*() function here.
 *
 * @param {object} tenant - DB row from tenants table (needs .email)
 * @param {{ subject: string, text: string, html: string }} rendered - from notificationEmailTemplateService.render()
 * @returns {Promise<{ sent: boolean }>}
 */
async function sendNotificationEmail(tenant, rendered) {
  const language = tenant.preferred_language || 'es';
  const { subject } = rendered;
  const { text, html } = applyStagingBanner(rendered, language);
  const provider = emailFactory.getProvider();

  await provider.send({
    from: `Comprobify <${config.email.from}>`,
    to: tenant.email,
    subject,
    text,
    html,
    attachments: [],
  });

  return { sent: true };
}

module.exports = {
  sendInvoiceAuthorized,
  sendVerificationEmail,
  sendPaymentProofSubmitted,
  sendNotificationEmail,
};
