const RejectionReasons = Object.freeze({
  AMOUNT_MISMATCH: 'AMOUNT_MISMATCH',
  TRANSFER_NOT_FOUND: 'TRANSFER_NOT_FOUND',
  WRONG_ACCOUNT: 'WRONG_ACCOUNT',
  ILLEGIBLE_PROOF: 'ILLEGIBLE_PROOF',
  DUPLICATE_SUBMISSION: 'DUPLICATE_SUBMISSION',
  OTHER: 'OTHER',
});

module.exports = RejectionReasons;
