/**
 * Webhook endpoint model.
 *
 * Tenant-scoped but not issuer-scoped — uses db.query() directly (no RLS context).
 */
const db = require('../config/database');

/**
 * Create a new webhook endpoint.
 *
 * @param {object} params
 * @param {number}   params.tenantId
 * @param {string}   params.url
 * @param {string}   params.secret      - 64-char hex generated by the service
 * @param {string[]} params.eventTypes  - empty array = subscribe to all event types
 */
async function create({ tenantId, url, secret, eventTypes = [], isReserved }, client = null) {
  const conn = client || db;
  const { rows } = await conn.query(
    `INSERT INTO webhook_endpoints (tenant_id, url, secret, event_types, is_reserved)
     VALUES ($1, $2, $3, $4, $5)
     RETURNING *`,
    [tenantId, url, secret, eventTypes, isReserved === true]
  );
  return rows[0];
}

/**
 * Return all active webhook endpoints for a tenant.
 * includeReserved: false (tenant-facing) hides comprobify-web's own endpoint; admin callers pass true.
 *
 * @param {number} tenantId
 */
async function findActiveByTenantId(tenantId, includeReserved = false) {
  const { rows } = await db.query(
    `SELECT * FROM webhook_endpoints
     WHERE tenant_id = $1 AND active = true
       AND ($2::boolean OR is_reserved = false)
     ORDER BY created_at ASC`,
    [tenantId, includeReserved]
  );
  return rows;
}

/**
 * Count active, non-reserved endpoints for a tenant (used to enforce tier limit).
 *
 * @param {number} tenantId
 */
async function countActiveByTenantId(tenantId) {
  const { rows } = await db.query(
    `SELECT COUNT(*) AS count FROM webhook_endpoints WHERE tenant_id = $1 AND active = true AND is_reserved = false`,
    [tenantId]
  );
  return parseInt(rows[0].count, 10);
}

// Bug/incident-detection ceiling only — see api-key.model.js#countReservedByTenantId.
async function countReservedByTenantId(tenantId) {
  const { rows } = await db.query(
    `SELECT COUNT(*) AS count FROM webhook_endpoints WHERE tenant_id = $1 AND active = true AND is_reserved = true`,
    [tenantId]
  );
  return parseInt(rows[0].count, 10);
}

/**
 * Find a single active endpoint by id + tenant (ownership check).
 *
 * @param {number} id
 * @param {number} tenantId
 */
async function findByIdAndTenantId(id, tenantId, client = null) {
  const conn = client || db;
  const { rows } = await conn.query(
    `SELECT * FROM webhook_endpoints WHERE id = $1 AND tenant_id = $2`,
    [id, tenantId]
  );
  return rows[0] || null;
}

/**
 * Update an endpoint's URL, event subscriptions, or active flag.
 *
 * @param {number} id
 * @param {{ url?: string, eventTypes?: string[], active?: boolean }} fields
 */
async function update(id, { url, eventTypes, active }, client = null) {
  const conn = client || db;
  const updates = [];
  const values  = [];
  let   idx     = 1;

  if (url !== undefined)        { updates.push(`url = $${idx++}`);          values.push(url); }
  if (eventTypes !== undefined) { updates.push(`event_types = $${idx++}`);  values.push(eventTypes); }
  if (active !== undefined)     { updates.push(`active = $${idx++}`);       values.push(active); }

  if (updates.length === 0) return null;

  updates.push(`updated_at = NOW()`);
  values.push(id);

  const { rows } = await conn.query(
    `UPDATE webhook_endpoints SET ${updates.join(', ')} WHERE id = $${idx} RETURNING *`,
    values
  );
  return rows[0] || null;
}

/**
 * Return all active endpoints for a tenant that subscribe to a given event type.
 * An endpoint with an empty event_types array receives ALL event types.
 *
 * @param {number} tenantId
 * @param {string} eventType  - NotificationTypes value
 */
async function findSubscribedByTenantIdAndType(tenantId, eventType) {
  const { rows } = await db.query(
    `SELECT * FROM webhook_endpoints
     WHERE tenant_id = $1
       AND active = true
       AND (event_types = '{}' OR $2 = ANY(event_types))`,
    [tenantId, eventType]
  );
  return rows;
}

module.exports = {
  create,
  findActiveByTenantId,
  countActiveByTenantId,
  countReservedByTenantId,
  findByIdAndTenantId,
  update,
  findSubscribedByTenantIdAndType,
};
